sudo: required
services:
  - docker
before_install:
  - docker build -t ripulchhabra/docker-react-test -f Dockerfile.dev .
  - docker build -t ripulchhabra/docker-react .
script:
  - docker run -e CI=true ripulchhabra/docker-react-test npm run test
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: loopback-connector-provider-re
  on:
    branch: master
  script:
    - docker run -e CI=true ripulchhabra/docker-react
